services:
  postgres-dev:
    extends:
      file: service.postgres.yml
      service: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  migrations:
    extends:
      file: service.migrations.yml
      service: migrations
    environment:
      - PGHOST=postgres-dev
      - ENV=development
    depends_on:
      postgres-dev:
        condition: service_healthy

  admin-service-dev:
    extends:
      file: service.admin-service.yml
      service: admin-service-dev
    depends_on:
        migrations:
          condition: service_completed_successfully

  worker:
    extends:
      file: service.worker.yml
      service: worker
    environment:
      - APP_URL=http://127.0.0.1:8081
      - PGHOST=postgres-dev
    depends_on:
      migrations:
        condition: service_completed_successfully

  rollup-admin-watch:
    extends:
      file: service.rollup-admin.yml
      service: rollup-admin-watch
    depends_on:
      admin-service-dev:
        condition: service_started

volumes:
  postgres_data_dev: