services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443" # Uncomment if SSL is configured
      - "8080:8080"
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../app_dist:/usr/share/nginx/app
      - ../../admin_dist:/usr/share/nginx/admin
      # For SSL certificates if needed
      # - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - app-network
